name: escooters
description: An application for displaying electric kick-scooters positions.
version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  flutter_bloc_patterns: ^0.4.0
  google_maps_flutter: ^0.5.25+1
  http: ^0.12.0+4
  intl: ^0.16.1
  json_annotation: ^3.0.1
  kiwi: 0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^4.0.0
  build_runner: ^1.7.2
  json_serializable: ^3.2.2
  kiwi_generator: 0.4.0
  lint: ^1.1.1
  mockito: ^4.1.1
flutter:
  uses-material-design: true