name: escooters
description: An application for displaying electric kick-scooters positions.
version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  flutter_bloc_patterns: ^0.6.0
  google_maps_flutter: ^1.0.3
  http: ^0.12.2
  intl: ^0.16.1
  json_annotation: ^3.1.0
  kiwi: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^4.0.0
  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  kiwi_generator: 2.0.1
  lint: ^1.3.0
  mockito: ^4.1.3
flutter:
  uses-material-design: true