name: escooters
description: An application for displaying electric kick-scooters positions.
version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  equatable: ^1.0.1
  flutter_bloc: ^2.0.1
  flutter_bloc_patterns: ^0.3.1
  google_maps_flutter: ^0.5.21+12
  http: ^0.12.0+2
  intl: ^0.16.0
  json_annotation: ^3.0.0
  kiwi: 0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.2
  kiwi_generator: 0.4.0
  mockito: ^4.1.1
flutter:
  uses-material-design: true