name: escooters
description: An application for displaying electric kick-scooters positions.
version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_bloc_patterns: ^0.9.0
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  kiwi: ^4.0.1

dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  kiwi_generator: ^4.0.1
  lint: ^1.8.2
  mocktail: ^0.2.0
flutter:
  uses-material-design: true