name: escooters
description: An application for displaying electric kick-scooters positions.
version: 1.0.0

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  equatable: ^0.6.1
  flutter_bloc: ^0.21.0
  http: ^0.12.0+2
  google_maps_flutter: ^0.5.21+7
  json_annotation: ^3.0.0
  kiwi: 0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  json_serializable: ^3.2.2
  kiwi_generator: 0.4.0
flutter:
  uses-material-design: true